# Generated by Django 4.0.5 on 2022-07-09 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='discription',
            new_name='description',
        ),
    ]
